openapi: 3.0.3
info:
  title: RTAC Cache API
  version: 1.0.0
paths:
  /rtac-cache/search/{instanceId}:
    get:
      tags:
        - rtac
      summary: Search RTAC holdings
      operationId: searchRtacCacheHoldings
      parameters:
        - name: instanceId
          in: path
          description: The UUID of a FOLIO instance
          required: true
          schema:
            type: string
            format: uuid
        - $ref: 'parameters/query-param.yaml'
        - $ref: 'parameters/available-param.yaml'
        - $ref: 'parameters/offset-param.yaml'
        - $ref: 'parameters/limit-param.yaml'
      responses:
        '200':
          description: RTAC holdings retrieved successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/rtacHoldings.json'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'
        '403':
          description: Access Denied
          content:
            text/plain:
              example: "Access Denied"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'
  /rtac-cache/{id}:
    get:
      tags:
        - rtac
      summary: Retrieve RTAC holdings for a single instance
      operationId: getRtacCacheHoldingsById
      parameters:
        - name: id
          in: path
          description: The UUID of a FOLIO instance
          required: true
          schema:
            type: string
            format: uuid
        - $ref: 'parameters/offset-param.yaml'
        - $ref: 'parameters/limit-param.yaml'
      responses:
        '200':
          description: RTAC holdings retrieved successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/rtacHoldings.json'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'
        '403':
          description: Access Denied
          content:
            text/plain:
              example: "Access Denied"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'

  /rtac-cache/batch:
    post:
      tags:
        - rtac
      summary: Retrieve RTAC holdings in batch
      operationId: postRtacCacheBatchHoldings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/rtacRequest.json'
      responses:
        '200':
          description: RTAC batch holdings retrieved successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/rtacHoldingsBatch.json'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'
        '403':
          description: Access Denied
          content:
            text/plain:
              example: "Access Denied"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'

components:
  schemas:
    RtacHolding:
      $ref: schemas/rtacHolding.json
    RtacRequest:
      $ref: schemas/rtacRequest.json
    RtacHoldingsBatch:
      $ref: schemas/rtacHoldingsBatch.json
    RtacHoldings:
      $ref: schemas/rtacHoldings.json
    RtacHoldingsSummary:
      $ref: schemas/rtacHoldingsSummary.json
    ResourceEvent:
      $ref: schemas/resourceEvent.json
    HoldingRecords:
      $ref: schemas/inventory/holdingsRecords.json
    Items:
      $ref: schemas/inventory/items.json
    Locations:
      $ref: schemas/inventory/locations.json
    Libraries:
      $ref: schemas/inventory/loclibs.json
    HoldingsNoteTypes:
      $ref: schemas/inventory/holdingsNoteTypes.json
    Loans:
      $ref: schemas/circulation/loans.json
    Requests:
      $ref: schemas/circulation/requests.json
    Pieces:
      $ref: schemas/orders/pieceCollection.json
    HoldingsFacet:
      $ref: schemas/search/holdingsFacet.json
    UserTenants:
      $ref: schemas/users/userTenants.json
    Settings:
      $ref: schemas/settings/settings.json
    MaterialTypes:
      $ref: schemas/inventory/materialTypes.json
    LoanTypes:
      $ref: schemas/inventory/loanTypes.json
