openapi: 3.0.3
info:
  title: RTAC Cache API
  version: 1.0.0
paths:
  /rtac-cache/{id}:
    get:
      summary: Retrieve RTAC holdings for a single instance
      operationId: getRtacCacheHoldingsById
      parameters:
        - name: id
          in: path
          description: The UUID of a FOLIO instance
          required: true
          schema:
            type: string
            format: uuid
        - $ref: 'parameters/offset-param.yaml'
        - $ref: 'parameters/limit-param.yaml'
      responses:
        '200':
          description: RTAC holdings retrieved successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/rtacHoldings.json'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'
        '403':
          description: Access Denied
          content:
            text/plain:
              example: "Access Denied"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'

  /rtac-cache-batch:
    post:
      summary: Retrieve RTAC holdings in batch
      operationId: postRtacCacheBatchHoldings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/rtacRequest.json'
      responses:
        '200':
          description: RTAC batch holdings retrieved successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/rtacHoldingsBatch.json'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'schemas/error.json'

components:
  schemas:
    rtacHolding:
      $ref: schemas/rtacHolding.json
    rtacRequest:
      $ref: schemas/rtacRequest.json
    rtacHoldingsBatch:
      $ref: schemas/rtacHoldingsBatch.json
    rtacHoldings:
      $ref: schemas/rtacHoldings.json
    rtacHoldingsSummary:
      $ref: schemas/rtacHoldingsSummary.json
    uuid:
      $ref: schemas/uuid.json
    error:
      $ref: schemas/error.json
    parameters:
      $ref: schemas/parameters.json
